name: Question
description: Ask a question about CurrentTime MCP Server
title: "[QUESTION] "
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide as much context as possible.
        
  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Ask your question here...
    validations:
      required: true
      
  - type: dropdown
    id: question_type
    attributes:
      label: Question Type
      description: What type of question is this?
      options:
        - Installation/Setup
        - Usage/How-to
        - Configuration
        - Troubleshooting
        - API/Development
        - Performance
        - Integration
        - Other
    validations:
      required: true
      
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're trying to accomplish
      placeholder: What are you trying to do? What's your use case?
      
  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What steps have you already taken?
      placeholder: Describe what you've already tried...
      
  - type: textarea
    id: environment
    attributes:
      label: Environment Information (if relevant)
      description: Information about your setup
      value: |
        - OS: [e.g. macOS 15.0, Windows 11, Ubuntu 22.04]
        - Python Version: [e.g. 3.11.5]
        - CurrentTime MCP Version: [e.g. 1.0.1]
        - Claude Code Version: [if applicable]
        - Installation Method: [uvx, pip, etc.]
      
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any other relevant information
      placeholder: Anything else that might help us answer your question...